### ISSUE TITLE
Export to calendar

### ISSUE THREAD

**Issue by holatom** [Dzoukr/Srazy.app-Project#1]
Please add function to export event to the calendar (.ics file, eg. MS Outlook) on event detail page.

**Comment by Dzoukr** [comment]
Great idea!

**Comment by Dzoukr** [comment]
![image](https://user-images.githubusercontent.com/851307/176860253-afec967e-6cce-41a1-9877-0366b558fb68.png)

Done 😉

**Comment by holatom** [comment]
Thanks
